### ISSUE TITLE
Strange folder names and several errors while downloading

### ISSUE THREAD

**Issue by infosec-us-team** [pratraut/scrapyFi#13]
Looks like something went wrong.

**Arguments:**
`search -q "Boson Protocol" -d`

**Output:**
![output](https://github.com/pratraut/scrapyFi/assets/93061989/994c6d2f-5495-462f-851a-9e2c8ff8b5c9)

**Errors:**

**1-** Folders named in the form of "''$'\n''SMART_CONTRACT_NAME'"

**2-** Several errors like these:
```
Downloading contract(s) from https://polygonscan.com/address/0xb27EF1bbeAfaaaD33339D8E12703d6c216c4dF8D#code:
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
Error: while downloading - Contract might be updated/deleted or contains bytecode
```

**Comment by pratraut** [comment]
Thank for reporting issue, we identified its an issue of newline introduced in etherscan page for contract name field. We fixed this issue in recent commit. Please check and reopen this issue if it persist. Closing it.
