### ISSUE TITLE
Regarding License

### ISSUE THREAD

**Issue by hans-cyfrin** [pratraut/scrapyFi#15]
Hi, @m0ham3dx @pratraut 

Do you mind adding explicit license terms to the repo?
Also I want to know if you are going to maintain this repo actively so that I can see PRs merged without too much delay going forward.

Thanks,

**Comment by m0ham3dx** [comment]
> Hi, @m0ham3dx @pratraut 
> 
> Do you mind adding explicit license terms to the repo?
> Also I want to know if you are going to maintain this repo actively so that I can see PRs merged without too much delay going forward.
> 
> Thanks,
> 
> 

Owner of this repo is @pratraut , and I have no role in its decisive actions

**Comment by pratraut** [comment]
> Hi, @m0ham3dx @pratraut
> 
> Do you mind adding explicit license terms to the repo? Also I want to know if you are going to maintain this repo actively so that I can see PRs merged without too much delay going forward.
> 
> Thanks,

Hi, Thanks for asking to add license. I have added MIT License to the repo and will be maintaining it going forward. Feel free to open Issues/PR

**Comment by hans-cyfrin** [comment]
Thank you!
